### ISSUE TITLE
Windows7 - still gives Error: connect ENOENT //./pipe/docker_engine

### ISSUE THREAD

**Issue by MarkPieszak** [dbashyal/Tips-And-Tricks#1]
Hey @dbashyal, so I followed your steps and everything, strangely still getting the same issue on Windows7. Is there anything I needed to do when I finished all those commands?

Also, I don't see the Docker whale in the task bar, not sure if that's part of the problem. (Since it's not there I can't select the "Use windows container" because of this). Not sure if that's Windows 10+ (and in beta) only though...

**Comment by dbashyal** [comment]
Hey @MarkPieszak , sorry I am not an expert in docker and I don't use it much at the moment. So, I have written down steps that works for me and I can refer when I use it again in future. 

The steps I mentioned always works for me so not sure about the issue on your case.

Also, I have uninstalled it from windows 7 machine at the moment, so I can't really help until I reinstall it again later.
